version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - method: "pip"
      path: "."

build:
  image: null

sphinx:
  builder: none

script:
    - pip install -r requirements.txt
    - sphinx-build -b html -d _build/doctrees . _build/html
